---
- name: CentOS | Install rpm
  ansible.builtin.get_url:
    url: "{{ twemproxy_download_url }}"
    dest: "{{ twemproxy_rpm }}"
    mode: "0644"
  become: true
  register: _rpm
  until: not _rpm.failed
  retries: 3
  delay: 3

- name: CentOS | Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ packages }}"
...
