---
- name: Delete | import common tasks
  tags:
    - memcached
    - pbos-infra
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | purge packages
  tags:
    - memcached
    - pbos-infra
  ansible.builtin.apt:
    name: "{{ item }}"
    purge: true
    state: absent
  loop: "{{ packages }}"
  become: true

- name: Delete | delete config directory
  tags:
    - memcached
    - openstack
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/memcached.conf
    - /etc/nutcracker
  become: true
...
