---
- name: Start | import common tasks
  tags:
    - memcached
    - pbos-infra
  ansible.builtin.import_tasks: "common.yml"

- name: Start | start service
  tags:
    - memcached
    - pbos-infra
  debug:
    msg: "Start {{ service_name }} service."
  changed_when: true
  notify:
    - systemctl restart service
...
